REFERENCIAS = {
    'Ur': {'min': 4.0, 'max': 34.0, 'unidade': 'mg/dL', 'material': 'SANGUE'},
    'Cr': {'min': 0.66, 'max': 1.25, 'unidade': 'mg/dL', 'material': 'SANGUE'},
    'Leucócitos': {'min': 4.0, 'max': 11.0, 'unidade': 'x 10³/µL', 'material': 'SANGUE'},
    'Neutr.': {'min': 2.0, 'max': 7.0, 'unidade': 'x 10³/µL', 'material': 'SANGUE'},
    'Eo.': {'min': 0.1, 'max': 0.5, 'unidade': 'x 10³/µL', 'material': 'SANGUE'},
    'Bas.': {'min': 0.0, 'max': 0.2, 'unidade': 'x 10³/µL', 'material': 'SANGUE'},
    'Mono.': {'min': 0.2, 'max': 1.0, 'unidade': 'x 10³/µL', 'material': 'SANGUE'},
    'Linf.': {'min': 1.0, 'max': 3.5, 'unidade': 'x 10³/µL', 'material': 'SANGUE'},
    'Hemácias': {'min': 4.5, 'max': 5.5, 'unidade': 'milhões/µL', 'material': 'SANGUE'},
    'Hb': {'min': 13.0, 'max': 17.5, 'unidade': 'g/dL', 'material': 'SANGUE'},
    'Ht': {'min': 40.0, 'max': 50.0, 'unidade': '%', 'material': 'SANGUE'},
    'VCM': {'min': 80.0, 'max': 100.0, 'unidade': 'fL', 'material': 'SANGUE'},
    'HCM': {'min': 26.0, 'max': 32.0, 'unidade': 'pg', 'material': 'SANGUE'},
    'CHCM': {'min': 32.0, 'max': 36.0, 'unidade': 'g/dL', 'material': 'SANGUE'},
    'RDW': {'min': 11.5, 'max': 14.5, 'unidade': '%', 'material': 'SANGUE'},
    'PLQ': {'min': 150.0, 'max': 450.0, 'unidade': 'x 10³/µL', 'material': 'SANGUE'},
    'PCR': {'min': 0.0, 'max': 5.0, 'unidade': 'mg/L', 'material': 'SANGUE'},
    'Mg': {'min': 1.6, 'max': 2.3, 'unidade': 'mg/dL', 'material': 'SANGUE'},
    'P': {'min': 2.5, 'max': 4.5, 'unidade': 'mg/dL', 'material': 'SANGUE'},
    'pH': {'min': 7.35, 'max': 7.45, 'unidade': '', 'material': 'SANGUE ARTERIAL'},
    'pO2': {'min': 83.0, 'max': 108.0, 'unidade': 'mmHg', 'material': 'SANGUE ARTERIAL'},
    'pCO2': {'min': 32.0, 'max': 48.0, 'unidade': 'mmHg', 'material': 'SANGUE ARTERIAL'},
    'HCO3': {'min': 21.0, 'max': 28.0, 'unidade': 'mmol/L', 'material': 'SANGUE ARTERIAL'},
    'BE': {'min': -2.0, 'max': 2.0, 'unidade': 'mmol/L', 'material': 'SANGUE ARTERIAL'},
    'Sat. O2': {'min': 95.0, 'max': 99.0, 'unidade': '%', 'material': 'SANGUE ARTERIAL'},
    'K (gaso)': {'min': 3.4, 'max': 4.5, 'unidade': 'mmol/L', 'material': 'SANGUE ARTERIAL'},
    'Na (gaso)': {'min': 136, 'max': 146, 'unidade': 'mmol/L', 'material': 'SANGUE ARTERIAL'},
    'Ca+ (gaso)': {'min': 1.15, 'max': 1.29, 'unidade': 'mmol/L', 'material': 'SANGUE ARTERIAL'},
    'Cl (gaso)': {'min': 98, 'max': 106, 'unidade': 'mmol/L', 'material': 'SANGUE ARTERIAL'},
    'Glicose': {'min': 70.0, 'max': 105.0, 'unidade': 'mg/dL', 'material': 'SANGUE ARTERIAL'},
    'Lactato': {'min': 0.0, 'max': 1.3, 'unidade': 'mmol/L', 'material': 'SANGUE ARTERIAL'}
}
